### ISSUE TITLE
OHDSI DatabaseConnector 

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu/CodelistGenerator#1]
At the moment this package uses DBI::dbConnect() to connect to a database, with dbplyr then used to work with the vocabularies. At the moment I wouldn't expect the code to work with a database connection established using the OHDSI DatabaseConnector::connect(), but this may be possible in the future (https://github.com/OHDSI/DatabaseConnector/issues/35 and https://github.com/OHDSI/DatabaseConnector/pull/175). Note to myself to update documentation etc if and when this becomes possible.

**Comment by edward-burn** [comment]
@ablack3 could you please advise on any changes in the status of your associated updates to DatabaseConnector (and let me know if this could be a useful place to test them), thanks!

**Comment by ablack3** [comment]
Hi Ed,

Yes I will. I'd really like to work with you on this. I think my approach will be to align more closely to the advice given by RStudio and build DatabaseConnector on top of DBI and allow it to use any DBI driver backend (many of which already work great with dplyr). https://db.rstudio.com/

Which database platforms are you using?

**Comment by edward-burn** [comment]
Fantastic, thanks @ablack3. Likely we'll be supporting postgres, redshift, and SQL server. The current approach to do a full network study requiring dbplyr code as well as ohdsi code would I suppose be to ask the user for two database connections, one DatabaseConnector and one DBI (using rpostgress and odbc). It would be great though if the databaseConnector could cover both (which I assume you agree with given your current branch!).

For this package, we don't use any ohdsi packages (which is why I only ask for the one DBI style connection), but hopefully it will still be a good test of whether an ohdsi style connection can be used instead.

Happy to talk more offline, or try any code you have on the databases I have access to.

**Comment by edward-burn** [comment]
Testing out the current implementation from @ablack3 as per https://github.com/OHDSI/DatabaseConnector/issues/185 and all seems to be working well for sql server

```
# DBI::dbConnect connection
library(DBI)
library(odbc)
library(dplyr)
library(dbplyr)
library(CodelistGenerator)
db_dbi <-DBI::dbConnect(odbc::odbc(),
                      Driver   = "ODBC Driver 11 for SQL Server",
                      Server   = Sys.getenv("darwinDbDatabaseServer"),
                      Database = Sys.getenv("darwinDbDatabase"),
                      UID      = Sys.getenv("darwinDbUser"),
                      PWD      = Sys.getenv("darwinDbPassword"),
                      Port     = Sys.getenv("darwinDbDatabasePort"))
codes1<-getCandidateCodes(keywords="dementia",
                     domains="Condition",
                     db=db_dbi,
                     vocabularyDatabaseSchema=Sys.getenv("darwinDbCdmSchema"),
                     verbose=TRUE)

# Adam´s DatabaseConnector connect
devtools::install_github("ablack3/DatabaseConnector", ref = "issue185", 
                         upgrade = "never", force = T)
library(DatabaseConnector)
details <-createConnectionDetails(odbc::odbc(),
                      Driver   = "ODBC Driver 11 for SQL Server",
                      Server   = Sys.getenv("darwinDbDatabaseServer"),
                      Database = Sys.getenv("darwinDbDatabase"),
                      UID      = Sys.getenv("darwinDbUser"),
                      PWD      = Sys.getenv("darwinDbPassword"),
                      Port     = Sys.getenv("darwinDbDatabasePort"))
db_DatabaseConnector <- connect(details)
vocabularyDatabaseSchema<-Sys.getenv("darwinDbCdmSchema")
codes2<-getCandidateCodes(keywords="dementia",
                     domains="Condition",
                     db=db_dbi,
                     vocabularyDatabaseSchema=Sys.getenv("darwinDbCdmSchema"),
                     verbose=TRUE)

# check they give the same result 
compareCodelists(codes1,codes2) %>% 
  group_by(codelist) %>% 
  tally()
```

**Comment by edward-burn** [comment]
Also to note, here we are using DBI::dbConnect() https://github.com/darwin-eu/CodelistGenerator/blob/260ee2decb6f07dc8f89c3a4312b61fd976ccf36/R/generateMockVocabDb.R#L116 to create a mock database for testing purposes, like here https://github.com/darwin-eu/CodelistGenerator/blob/260ee2decb6f07dc8f89c3a4312b61fd976ccf36/tests/testthat/test-getCandidateCodes.R#L8

@ablack3 please advise when your code works for SQLite (and/or duckdb) and we could try and use it for these tests

**Comment by edward-burn** [comment]
Closing as this will be via CDMConnector rather than DatabaseConnector
