### ISSUE TITLE
Missing Function Explanation

### ISSUE THREAD

**Issue by PRijnbeek** [darwin-eu/CodelistGenerator#108]
https://github.com/darwin-eu/CodelistGenerator/blob/a3bc823a250b0153b6e275851b04d56b754141d5/R/runSearch.R#L17

please add a detailed function specification that describes how the search is performed

**Comment by edward-burn** [comment]
We have these two vignettes https://darwin-eu.github.io/CodelistGenerator/articles/a02_Candidate_codes_OA.html and https://darwin-eu.github.io/CodelistGenerator/articles/a03_Options_for_CodelistGenerator.html which hopefully provide plenty of details on what the options are for the search
