### ISSUE TITLE
Running codelist generator locally on vocabs not present in a users cdm database

### ISSUE THREAD

**Issue by daniellenewby** [darwin-eu/CodelistGenerator#109]
**Is your feature request related to a problem? Please describe.**
When carrying out studies particulary oncology users wont have the cancer standard vocab ICDO3 on their CDM database. So codelist generator will not give codelists related to ICDO3 codes in this case. The issue is alot of cancer registries cannot map alot of ICDO3 codes to SNOMED therefore if this data partners are not leading the study then codes can be missed due to lack of ICDO3 vocab.

**Describe the solution you'd like**
The user can download the vocabs such as ICDO3 from athena and work locally with codelist generator to generate codes that generate SNOMED and ICDO3

**Describe alternatives you've considered**
You can find the ICDO3 codes you need then map by relationship with SNOMED codes but this doesnt help if you dont know which ICDO3 codes to start with.

**Additional context**
This will help with phenotyping to generate oncology phenotypes with both SNOMED and ICDO3 vocabs with study leads who dont have access to databases containing ICDO3 vocabs

**Comment by edward-burn** [comment]
closing - moved to darwin-dev repo
