### ISSUE TITLE
achillesCodeUse to return empty dataframe with same columns

### ISSUE THREAD

**Issue by albertpratsu** [darwin-eu/CodelistGenerator#116]
**Describe the bug**
When running achillesCodeUse, if the codes are not found in the database, it returns an empty tibble ( 0 × 0). 
It would be useful to have a predictable output, with the same column names as the usual output but 0 rows, or the concept ids but NA in counts.

**Comment by edward-burn** [comment]
Yes good point @albertpratsu, when we integrate omopgenerics we can use 
https://darwin-eu-dev.github.io/omopgenerics/reference/emptySummarisedResult.html to do this

**Comment by edward-burn** [comment]
fixed
