### ISSUE TITLE
Not working with Databricks

### ISSUE THREAD

**Issue by laacdm** [darwin-eu/CodelistGenerator#137]
**Describe the bug**
Communication link failure.

**To Reproduce**
con <- DatabaseConnector::connect(connectionDetails)

cdm <- CDMConnector::cdm_from_con(
  con,
  cdm_schema = "xxxx",
  write_schema = c(schema = "xxxx", prefix = "xxxx")
)
conceptList <- CodelistGenerator::getDrugIngredientCodes(cdm, "acetaminophen")

**Expected behavior**
A table with a list of codes

**Screenshots**
![results29](https://github.com/darwin-eu/CodelistGenerator/assets/26804329/daeb48a3-b49b-425a-b87b-45bc65e2d127)

**Platform:**
- OS: x86_64-pc-linux-gnu
- R version: 4.2.3 (2023-03-15)
- Browser Chrome
- Version 120

**Comment by edward-burn** [comment]
Hi @laacdm, sorry to be slow to get back to you but this should I think work if you use the odbc driver like below. Does that work for you? (I can't guarantee much though as CDMConnector is not yet fully tested against databricks) 

```
library(DBI)
library(CDMConnector)

# using odbc useNativeQuery = TRUE
db <- DBI::dbConnect(
  odbc::databricks(),
  httpPath = "....",
  workspace = "....",
  uid = "token",
  pwd = "....",
  useNativeQuery = FALSE)

cdm <- cdm_from_con(con = db,
                    cdm_schema = "....",
                    write_schema = "....",
                    cdm_name = "my databricks database")
```

**Comment by edward-burn** [comment]
@laacdm hopefully the above worked - am closing because I assume you would have said if it didn´t, but please reopen if you are still having this problem
