### ISSUE TITLE
question about summariseCodeUse()

### ISSUE THREAD

**Issue by tiozab** [darwin-eu/CodelistGenerator#145]
https://darwin-eu.github.io/CodelistGenerator/reference/summariseCodeUse.html
the example lists several concept ids for paracetamol, yet, only the ingredient level is depicted in the results. Is that the idea?
the default for byConcept = TRUE, should I then not expect a bit more detailed results?

the description says 
"byConcept
TRUE or FALSE. If TRUE code use will be summarised by ..." the by "what" is missing.

**Comment by edward-burn** [comment]
I think we looked at this right @tiozab and this was because the test data you were using only for ingredient level concepts. So am closing, but please reopen if this was a different issue
