### ISSUE TITLE
CodeCov not updated

### ISSUE THREAD

**Issue by PRijnbeek** [darwin-eu/CodelistGenerator#147]
**Describe the bug**
Last time CodeCov was executed is 12 months ago

**To Reproduce**
Click on the badge

**Expected behavior**
Executed with each push/commit to main

**Comment by edward-burn** [comment]
@PRijnbeek sure, if you could please send me the token I can add this.

**Comment by edward-burn** [comment]
closing - moved to darwin-dev repo
