### ISSUE TITLE
Helper function for icd names

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu/CodelistGenerator#158]
availableICD10(cdm) - returns the names of the icd concepts. This would help users know what they can put as a name in the getICD10StandardCodes() function

**Comment by xihang-chen** [comment]
hey @edward-burn do we want to make a distinction of chapters and subchapters for this helper function as well? 

I am thinking if i should use vocabury_id or concept_class_id for this
![question](https://github.com/darwin-eu/CodelistGenerator/assets/114928037/98cd3ed3-d321-4380-ad13-ae9ef6310b42)
