### ISSUE TITLE
summariseOrphanCodes() error with three codes

### ISSUE THREAD

**Issue by xihang-chen** [darwin-eu/CodelistGenerator#160]
**Describe the bug:**
On Eunomia when running the following code it threw an error: 

`concussion_cs <- list(concussion = c(378001, 375671, 4001336)) 
concussion_orphan_codes <- summariseOrphanCodes(concussion_cs, 
                                                cdm = cdm,
                                                domains = c("condition"))
`

**Error:**
`
Error in `dplyr::select()`:
! Can't select columns that don't exist.
✖ Column `source_concept_name` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.
`

We also observed that with 2 of these codes or fewer, the codes ran fine.

**Comment by edward-burn** [comment]
now fixed
