### ISSUE TITLE
getCandidateCodes() Search returning code from domain not specified in search argument

### ISSUE THREAD

**Issue by daniellenewby** [darwin-eu/CodelistGenerator#162]
**Describe the bug**
I am doing a search in the observation and condition vocabs for breast cancer.  In my results there was a code that is a descendant code in the measurements domain (see screenshot). I am using downloaded vocabs from athena to do this. 

**To Reproduce**
breastcancer_codes <- getCandidateCodes(
  cdm = cdm,
  keywords = c("malignant neoplasm of breast",
               "neoplasm of breast") ,
  domains = c("Condition", "Observation"),
  standardConcept = "Standard",
  searchInSynonyms = FALSE,
  searchNonStandard = FALSE,
  includeDescendants = TRUE,
  includeAncestor = FALSE
)

**Expected behavior**
I expected the descendants or outputs from codelist generator would be restricted to observation and conditions codes and would not expect codes related to measurement.

**Screenshots**
![image](https://github.com/darwin-eu/CodelistGenerator/assets/16097637/4649b413-da14-4276-b4d8-24a8bc5a4114)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Additional context**

**Comment by edward-burn** [comment]
thanks for reporting @daniellenewby, this should now be fixed
