### ISSUE TITLE
Failing test for fuzzy search

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu/CodelistGenerator#17]
**Describe the bug**
@MimiYuchenGuo can you please take a look at this test which is failing: https://github.com/darwin-eu/CodelistGenerator/blob/0bfd8ac44d93c70cfb2d4dba3f136e218379b4e0/tests/testthat/test-get_candidate_codes.R#L54
I was taking a look at the code and it seems to work if we go back and just have max.distance=0.2, rather than the three options, then "Osteoarthrosis" is picked up.

**To Reproduce**
1. Uncomment the test and run - does it also fail for you?

**Expected behavior**
This code should be identifying "Osteoarthrosis" - see [this vignette](https://darwin-eu.github.io/CodelistGenerator/articles/a02a_Options_for_CodelistGenerator.html), under the heading "Fuzzy matches instead of only exact matches"

**Comment by MimiYuchenGuo** [comment]
I have added new parameters in fuzzy matching that can solve this problem. Please let me know if otherwise. Thank you
