### ISSUE TITLE
Output of codesFromConceptSet

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu/CodelistGenerator#205]
Should the output of codesFromConceptSet be a codelist? instead of a list of concept ids? @edward-burn

**Comment by edward-burn** [comment]
@catalamarti yes, it should work like that from 3.1.0. Do you see something different from the below?

``` r
library(CodelistGenerator)
packageVersion("CodelistGenerator")
#> [1] '3.1.0'
cdm <- mockVocabRef()
codesFromCohort(
  cdm = cdm, path =  system.file(package = "CodelistGenerator",
                                 "cohorts_for_mock_with_exclude"), 
  type = "codelist"
)
#> 
#> ── 2 codelists ─────────────────────────────────────────────────────────────────
#> 
#> - OA (2 codes)
#> - Other (1 codes)
```

<sup>Created on 2024-07-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by catalamarti** [comment]
error was due to old version of CodelistGenerator
