### ISSUE TITLE
Error in `auto_copy()`: when searchInSynonyms is FALSE

### ISSUE THREAD

**Issue by zcuccu** [darwin-eu/CodelistGenerator#212]
Error in `auto_copy()`:
! `x` and `y` must share the same src.

codes <- getCandidateCodes(cdm = cdm,
                           keywords = "weight",
                           exclude = c("ratio", "percent"),
                           domains = "Measurement",
                           standardConcept = "Standard",
                           searchInSynonyms = FALSE,
                           searchNonStandard = FALSE,
                           includeDescendants = FALSE,
                           includeAncestor = FALSE)

**Comment by edward-burn** [comment]
hi @zcuccu sorry for being slow to get back to you, can I check if you are still having this problem with the latest version of the package?

**Comment by zcuccu** [comment]
Hi @edward-burn this is for version 3.0, can confirm I don't have this issue with the latest version 3.2.1

**Comment by edward-burn** [comment]
Grateful!
