### ISSUE TITLE
`groupColumns` --> `groupColumn`

### ISSUE THREAD

**Issue by nmercadeb** [darwin-eu/CodelistGenerator#221]
In tables I used the plural for the groupColumn argument but to be consistent with visOmopResults and the argument naming in the packages I think it should be singular. @edward-burn I dont know if you think it would be worth to change?

https://github.com/darwin-eu/CodelistGenerator/blob/6b19b33c294b522a2a465663bd78cb2148cc1a54/R/tableCodeUse.R#L56

**Comment by edward-burn** [comment]
closing - moved to darwin-dev repo
