### ISSUE TITLE
kable in readme needs to have library specified

### ISSUE THREAD

**Issue by rossdwilliams** [darwin-eu/CodelistGenerator#23]
**Describe the bug**
When running the code in the readme, the kable function fails as it cant be found

**To Reproduce**
run the readme in a fresh R session without importing knitr

**Expected behavior**
knitr::kable() would likely fix the issue

**Comment by edward-burn** [comment]
Thanks for spotting this @rossdwilliams, please can you check the current readme where hopefully this is now fixed?
