### ISSUE TITLE
getAtcCodes to support concept_code 

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu/CodelistGenerator#231]
It would be nice if instead of having to provide:
`desogestrel and ethinylestradiol; systemic (progestogens and estrogens, fixed comb.)`
we could just provide the ATC code:
`G03AA09`

This is a issue that we found in @xihang-chen study

@edward-burn  would you be happy that name argument supports either of them?

**Comment by edward-burn** [comment]
moved to darwin dev issues
