### ISSUE TITLE
Rename functions for consistent naming conventions

### ISSUE THREAD

**Issue by ablack3** [darwin-eu/CodelistGenerator#33]
The importVocab function downloads vocabulary table from a database to a specified file location. I think we should be very careful about naming and how we use certain words that can have multiple meanings. If a user can associate certain words with specific meanings it will make the interface easier to use.

For example in the tidyverse world, "tidy" has a very specific meaning related to the idea of ["tidy data"](https://vita.had.co.nz/papers/tidy-data.pdf). 

Let's think of terms we might want to use and then try to use them consistently across all DARWIN tools.

**tidy** is a verb that means return the input in the tidy data format (one row per observation, one column per variable)

![image](https://user-images.githubusercontent.com/10227522/184671501-5253dc47-5a6a-466b-b24b-8bffb1690860.png)

**Verbs (actions or calculation)**
The verbs in our lexicon refer to actions (side effects) or calculations (returns a value with no side effects) that are performed. I'll write more about the difference between actions and calculations in the developer docs but for this issue we just want to make sure each verb either refers to an action or calculation but not both. https://design.tidyverse.org/side-effect-soup.html#side-effect-soup

- get
- set
- download
- save
- generate : Combine a particular CDM database with a specification to produce a result (e.g. cohort table). The signature for generate should always be something like `result <- generate(cdm, specification)`
- show: In many programming languages including R "show" refers to printing output to the console/stdout.
- compare

**Nouns (data)**
The nouns refer to the static data that is being created or acted upon.
- candidateCodeList
- Codelist
- Mappings
- mockVocabDb
- VocabReference?

I'd like to discuss some of these terms here and then add them to the developer documentation. To get a consistent user experience across the tools we need consistent naming of functions and objects.

https://design.tidyverse.org/function-names.html

**Concrete suggestions to discuss**

Rename `importVocab` to `downloadVocab` because I'm not sure what import refers to here. Import is often used to load a module similar to the `library` function in R. Download seems to be a better fit since we are extracting data from a remote database server.

Rename `gereateMockVocabDb` to `mockVocabRef` (or whatever we call the vocab reference object).
Generate already has a very specific meaning in OHDSI tools.

Rename `ShowMappings` to `getMappings`.
Show means the same thing as `print`.

We could also consider how we want to use the dplyr verbs "collect" and "pull" which refer to extracting data from a remote database or Arrow table.

**Comment by edward-burn** [comment]
Yes, seems we need to make a policy for naming conventions, but all the above sounds sensible.

For these specific cases the suggested changes make sense to me, so let´s change
-  importVocab to downloadVocab
-  showMappings to getMappings

Maybe for gereateMockVocabDb, it can change to mockVocab (as we´re creating a mock vocabulary, not just a reference)?

**Comment by edward-burn** [comment]
@ablack3 I have changed importVocab to downloadVocab, showMappings to getMappings, gereateMockVocabDb to mockVocab, and I have also made tidyWords an internal function as that is just for use in the getCandidateCodes function anyway. With that, do all the function names sound ok to you?

**Comment by edward-burn** [comment]
Closing this as I think it is done. @ablack3 please reopen if you had any additional comments
