### ISSUE TITLE
CodelistGenerator Code Review 

### ISSUE THREAD

**Issue by ablack3** [darwin-eu/CodelistGenerator#34]
@edward-burn How about we use this issue to track the code review. I also opened two other issues to discuss specific recommendations.

At a high level the topics I'd like to discuss are:

- CodelistGenerator requirements: What is the need CodelistGenerator is filling that is not currently fulfilled by Atlas search? It looks like you're trying to create a new version of concept set creation interface in Shiny. Is it the generation of code for traceability that is lacking?
- Use of a single "data" object that is a list of vocabulary tables or table references (separate issue)
- Consistent function and argument naming conventions (separate issue)

I also want to highlight that mapping free text onto concepts ("the search problem") is going to be best handled by something like [Solr](https://solr.apache.org/) (which is available in Atlas Search and used by Athena). Can we separate the responsibility of creating a code based "search trace" from the responsibility of actually performing the search. For example suppose the search functionality was behind a REST API (e.g. Athena) and CodeListGenerator would send queries to the endpoint and get results back accepting the search algorithm as a black box? Does the search algorithm need to be implemented in SQL?

What are the other requirements of this package?
- Support offline search (no remote CDM database)
- Search "code trace"?
- Reproducibility? (Run the same query in the future to get the same results?)

**Comment by edward-burn** [comment]
@ablack3 we now have the SRS which better explains where CodelistGenerator fits compared to other tools. I think this addresses the above, but if not let´s discuss further
