### ISSUE TITLE
Clarification on synonym search

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu/CodelistGenerator#35]
## Current behaviour

At the moment the way the synonym search works is that in that it will look at the synonyms of the codes found from an initial search and then do another search for these synonyms.

So in the below example the synonym search will find that "ostearthrosis" is a synonym of "arthritis" and it will go and find the code that has ostearthrosis as it´s name.

Without synonym search
![imagen](https://user-images.githubusercontent.com/9583964/185376122-b925ce30-7f04-4f7c-b4ba-f8a40cf3e779.png)

With synonym
![imagen](https://user-images.githubusercontent.com/9583964/185376175-0f39e372-c342-4ace-8bd5-e3b95d54035c.png)

## Change in or additional behaviour
Another way to use the synonym table would be to search directly in that to find concepts. So for example, if in the above "ostearthrosis"  had a synonym of "arthritis" rather than "ostearthrosis" being a synonym of "arthritis" our current synonym search wouldn´t pick it up. But doing a direct search of the synonym table would.

**Comment by edward-burn** [comment]
@albertpratsu does the above summarise what we were talking about? If we want the additional behaviour we could
1) have search synonym do both of the above,
2) replace the current approach with the alternative approach,
3) have two options instead of one (e.g. "searchViaSynonym" for the current behaviour and "searchFromSynonym" for the alternative)

Do you have any strong preferences?

Also tagging @daniellenewby and @ajoedicke as you are the current user base in case you have any thoughts on this :)

**Comment by daniellenewby** [comment]
I think capturing all would be good (so point 1 from above) as this is a tool that grabs a list which then we refine. So its a starting point however we don't want thousands of results that might happen if we have both approaches combined.  I worry having too many options will overcomplicate things so if you want to go down point 3) we would have to make the vignette very clear with a few specific examples of why you would use each different option - there are my thoughts - i want to get a list of codes with as few steps as possible and not with lots of options :)

**Comment by edward-burn** [comment]
Ok, I'll implement option 3. I'll keep both defaults as FALSE for the time being, but yes let's further evaluate the defaults in general

To do 
- [ ]  change "searchSynonyms" to "searchViaSynonyms" (current implementation)
- [ ] add "searchInSynonyms" (additional functionality)

**Comment by edward-burn** [comment]
"searchSynonyms" to "searchViaSynonyms" done here https://github.com/darwin-eu/CodelistGenerator/commit/bb7ffcfb9df6567c6127b29e57ae691ee78887c9

**Comment by edward-burn** [comment]
searchInSynonyms added here https://github.com/darwin-eu/CodelistGenerator/commit/7797f4121342230278374cfcbf5f13c7e58085a0

**Comment by edward-burn** [comment]
updated vignettes accordingly here https://github.com/darwin-eu/CodelistGenerator/commit/52832eb98d04b0682ddb2ba204334c475543c875
