### ISSUE TITLE
Add a function to create a simple cohort

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu/CodelistGenerator#44]
If we have a function that allows us to create a concept set from a list of concepts (saveConceptSet).
It would be nice to have a function to create a cohort from the concept set (or the list of concepts) so that we can run a cohortDiagnostics. This is a petition from the users @albertpratsu .
Then input parameters would be:
- list of concepts or concept set
- prior observation days
- I dont know if you have any other extra input that you want to include @albertpratsu ? 
The output would be a json file or the cohort definition. Do you think that this is feasible @Xintong-Li-ZnCu ?

**Comment by Xintong-Li-ZnCu** [comment]
My question would then be, after the "simple" cohort for running cohort diagnostics, you still need to modify the cohort using other tools like ATLAS. Would it be easier to keep all the cohort related thing on one side and the package just for concept set instead?

**Comment by edward-burn** [comment]
Sorry @catalamarti @albertpratsu, this is is out of scope for this package. This functionality should, I think, be provided by other tools (ATLAS, capr, or something else)
