### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by ablack3** [darwin-eu/CodelistGenerator#46]
The maintainer, currently @edward-burn, should submit to cran using `devtools::submit_cran()`. An email will be sent with a confirmation link.

If you want someone else to submit then I think that person should be the maintainer (i.e. the person responsible for package releases)

Before doing this make sure R check is passing on all platforms, create a cran_comments.md file. Also consider running R check on winbuilder using `devtools::check_win_release()`

Be prepared to submit multiple times. If it fails R check on cran servers do not email cran. Just try to fix the error and resubmit.

Check out https://r-pkgs.org/release.html

**Comment by edward-burn** [comment]
https://cran.r-project.org/web/packages/CodelistGenerator/
