### ISSUE TITLE
Addition of a codelist suggestions feature

### ISSUE THREAD

**Issue by albertpratsu** [darwin-eu/CodelistGenerator#47]
**Is your feature request related to a problem? Please describe.**
It would be outstanding to have a feature that suggests codes that may have been missed after the clinical screening. Something similar to orphan codes in CohortDiagnostics but without the codes, totally database agnostic.

**Describe the solution you'd like**
A search based suggestion of codes similar to this: https://github.com/OHDSI/CohortDiagnostics/blob/main/inst/sql/sql_server/OrphanCodes.sql 

**Describe alternatives you've considered**
CohortDiagnostics does this but needs to be run on a database. Having it in here would further refine the codelist before running anything.

**Comment by edward-burn** [comment]
@albertpratsu yes this should be possible and sounds like it would be useful. So in terms of workflow, this would come after screening codes, and then the user would pass their reviewed codes and we would return a list of suggested orphan codes that they could consider (e.g. based on synonyms, mapping etc from the codes they have chosen to include)?

**Comment by edward-burn** [comment]
findOrphanCodes has been added to the package
