### ISSUE TITLE
Map from codelist using a non-standard vocabulary to a standard vocabulary

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu/CodelistGenerator#49]
Multiple users (@daniellenewby @ajoedicke @albertpratsu  @Braventos @arani11) seem to be interested in mapping from a code list in a non-standard format (e.g. icd-10, read, etc) to standard vocabularies. I can imagine this could be useful both for creating the code list for a study, but also to be able to compare a code list you have created to those used in other studies using source data.

@daniellenewby @Braventos perhaps we could use the ICD anxiety/ depression codes to help prototype this feature, if you still think it would be useful?

**Comment by daniellenewby** [comment]
Yes, still think this would be super useful if it is easy to implement without any breaking changes to the package ;)

**Comment by arani11** [comment]
Yes that would be really helpful thanks
