### ISSUE TITLE
library(kableExtra) needs installation first

### ISSUE THREAD

**Issue by tiozab** [darwin-eu/CodelistGenerator#53]
for readme and vignette: kableExtra library cannot be loaded, the package needs to be installed first (does not come with CodeList Generator)

**Comment by tiozab** [comment]
same is true for DT, the package DT needs to be installed first

**Comment by edward-burn** [comment]
kableExtra and DT are in suggests not imports as per https://r-pkgs.org/description.html#sec-description-imports-suggests (ie not needed at runtime but are used by developers etc)
