### ISSUE TITLE
vignette synonyms

### ISSUE THREAD

**Issue by tiozab** [darwin-eu/CodelistGenerator#61]
the vignette is not very clear on what the difference is "inSynonyms" and "viaSynonyms". 
I was told that one picks up only the synonyms, but the other gives me the results as if the synonym was searched for as a search term ?!

**Comment by edward-burn** [comment]
It's explained in this vignette: https://darwin-eu.github.io/CodelistGenerator/articles/a03_Options_for_CodelistGenerator.html#search-using-synonyms 

"We can also pick up codes based on their synonyms. In this case “Arthritis” has a synonym of “Osteoarthrosis” and so a search of both the primary name of a concept and any of its associated synonyms would pick up this synonym and it would be included."

"Or, in this case, we can get the same result by searching via synonyms. In this case when using searchViaSynonyms=TRUE, “Arthritis” (which gets identified first) has a synonym of “Osteoarthrosis”, and based on this synonym we can also include the “Osteoarthrosis” concept."

As in the difference is whether you look at the synonyms of concepts for the key word (searchInSynonyms),  or whether you look at the synomyns of the concepts that are identified from the initial search (searchViaSynonyms). Does that make sense?

**Comment by edward-burn** [comment]
Will consider here https://github.com/darwin-eu/CodelistGenerator/issues/69 whether to merge these two options into one (if we keep both separately then will review the documentation for them)
