### ISSUE TITLE
tiny words

### ISSUE THREAD

**Issue by tiozab** [darwin-eu/CodelistGenerator#63]
there are some tiny words in search terms which means that the larger word is found, e.g. "pots" yields all the "spots", or "liver" yields all the "deliveries". I was wondering if there is a smarter way to prevent this than excluding the unwanted term from the search

**Comment by edward-burn** [comment]
Once https://github.com/darwin-eu/CodelistGenerator/issues/54 is implemented the user can then use the exact matching option which should help. Not sure we can do more beyond that, unless there is something solution I'm missing?
