### ISSUE TITLE
"restrict on dose form" in vignette

### ISSUE THREAD

**Issue by tiozab** [darwin-eu/CodelistGenerator#65]
The vignette reads "Restrict on dose form
We can also restrict on dose form, in this case requiring dose form to include either “injection” or “intravenous” in it’s name."

In fact, the concept name is often "injectable ... ", so the save way is to search for "inject" and addtionally for "IV" "IM" e.g.

**Comment by edward-burn** [comment]
updated in https://github.com/darwin-eu/CodelistGenerator/pull/70
