### ISSUE TITLE
Consider merging searchInSynonyms and searchViaSynonyms

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu/CodelistGenerator#69]
Having `searchInSynonyms` and `searchViaSynonyms` as separate options in getCandidateCodes() has led to questions from multiple users about the difference between the two. It seems like we should consider merging into a single option `searchSynonyms`

**Comment by tiozab** [comment]
Hi, I want to follow up on this item. I think this is very crucial to have a meaningful search through codelistgenerator. Therefore, I am very much in favour that the synonyms are automatically searched as if their names were put into the keywords (I assume this is the "via" route right now?). It is impossible to know all the synonyms a medical dictionary may come up with. At the same time, the "in" route where the synonyms are also a result of the search are also important, so I agree to combine the two :-) And make it very clear in the vignette, I am happy to help rephrasing the vignette :-)
