### ISSUE TITLE
Breaking change in CDMConnector v1.0 

### ISSUE THREAD

**Issue by ablack3** [darwin-eu/CodelistGenerator#78]
CDMConnector v1.0 removed the cdm_tables argument from cdm_from_con. Please remove the argument from all calls to cdm_from_con or cdm_from_files.

https://github.com/search?q=repo%3Adarwin-eu%2FCodelistGenerator%20cdm_tables%20%3D%20&type=code

**Comment by edward-burn** [comment]
done in last cran release!
