### ISSUE TITLE
NA name of concepts in summariseCodeUse

### ISSUE THREAD

**Issue by albertpratsu** [darwin-eu/CodelistGenerator#90]
**Describe the bug**
When using summariseCodeUse with only person counts the name of the concepts show NA (NA)

**Additional context**
This line of code seems to be the culprit:
  if (!"record" %in% countBy) {
    codeCounts <- codeCounts %>% dplyr::mutate(concept_name = NA, 
                                               concept_id = NA)
  }

**Comment by edward-burn** [comment]
@albertpratsu thanks for reporting, this should be fixed in the latest release (please reopen if you still have this problem)
