### ISSUE TITLE
error to compute the ATC codes

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu/CodelistGenerator#91]
![image](https://github.com/darwin-eu/CodelistGenerator/assets/18575244/13fa3ad7-2c6e-4a91-9b06-982f9c4107f9)

We have debugged with @ilovemane and found the error is in: https://github.com/darwin-eu/CodelistGenerator/blob/a8c44bc41dd1b89accf3e5ca8e3fa4f0c90f2729/R/vocabUtilities.R#L378-L380

The error was found in gold202207

**Comment by edward-burn** [comment]
Thanks for reporting @catalamarti and @ilovemane, this should be fixed in the latest reslease (if not, please reopen the issue)
