### ISSUE TITLE
Changes to CDM Connector  may have broken connecting to a CDM from files

### ISSUE THREAD

**Issue by albertpratsu** [darwin-eu/CodelistGenerator#97]
cdm <- CDMConnector::cdm_from_files(path = vocab_path, cdm_name = "Vocab",
                                           as_data_frame = FALSE)
 getVocabVersion(cdm = cdm)   ## Should output: "v5.0 21-AUG-20"
[1] "v5.0 21-AUG-20"
 phenotype_codes <- getCandidateCodes( cdm=cdm,
                                                keywords = "Hepatic Failure",
                                                 domains = c("Condition", "Observation"),
                                                 standardConcept = "Standard",
                                                 searchInSynonyms = T,
                                                 searchViaSynonyms = F,
                                                 searchNonStandard = T,
                                                 includeDescendants = T,
                                                 includeAncestor = F,
                                                 verbose=TRUE  )

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbIsValid’ for signature ‘"NULL"’

**Comment by edward-burn** [comment]
Thanks for reporting @albertpratsu, I'll take a look and get back to you
