### ISSUE TITLE
tidywords UTF-8 error

### ISSUE THREAD

**Issue by albertpratsu** [darwin-eu/CodelistGenerator#98]
**Describe the bug**
Codelist Generator when checking the Observation table gives an error in some computers. (Using an offline vocabulary CDM from files)

**Screenshots**
<img width="768" alt="MicrosoftTeams-image (1)" src="https://github.com/darwin-eu/CodelistGenerator/assets/44193724/0c75536f-e3bc-4390-9884-cacdf0b50272">

**Desktop (please complete the following information):**
 - Device: Mac Computer

**Comment by edward-burn** [comment]
@albertpratsu can you still see if this is an issue with v2.0? (and if it is please put me in touch as I can look with them as it is a hard one for me to reproduce)

**Comment by edward-burn** [comment]
Assume this is all working nowadays @albertpratsu (but please reopen if not!)
